/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWajibPajakRouteImport } from './routes/_authenticated.wajib-pajak'
import { Route as AuthenticatedDokumenRouteImport } from './routes/_authenticated.dokumen'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDokumenIndexRouteImport } from './routes/_authenticated.dokumen.index'
import { Route as ApiDocumentsSlugRouteImport } from './routes/api.documents.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthenticatedDokumenSlugRouteImport } from './routes/_authenticated.dokumen.$slug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWajibPajakRoute = AuthenticatedWajibPajakRouteImport.update({
  id: '/wajib-pajak',
  path: '/wajib-pajak',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDokumenRoute = AuthenticatedDokumenRouteImport.update({
  id: '/dokumen',
  path: '/dokumen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDokumenIndexRoute =
  AuthenticatedDokumenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDokumenRoute,
  } as any)
const ApiDocumentsSlugRoute = ApiDocumentsSlugRouteImport.update({
  id: '/api/documents/$slug',
  path: '/api/documents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDokumenSlugRoute =
  AuthenticatedDokumenSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedDokumenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokumen': typeof AuthenticatedDokumenRouteWithChildren
  '/wajib-pajak': typeof AuthenticatedWajibPajakRoute
  '/dokumen/$slug': typeof AuthenticatedDokumenSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$slug': typeof ApiDocumentsSlugRoute
  '/dokumen/': typeof AuthenticatedDokumenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/wajib-pajak': typeof AuthenticatedWajibPajakRoute
  '/dokumen/$slug': typeof AuthenticatedDokumenSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$slug': typeof ApiDocumentsSlugRoute
  '/dokumen': typeof AuthenticatedDokumenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dokumen': typeof AuthenticatedDokumenRouteWithChildren
  '/_authenticated/wajib-pajak': typeof AuthenticatedWajibPajakRoute
  '/_authenticated/dokumen/$slug': typeof AuthenticatedDokumenSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$slug': typeof ApiDocumentsSlugRoute
  '/_authenticated/dokumen/': typeof AuthenticatedDokumenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dokumen'
    | '/wajib-pajak'
    | '/dokumen/$slug'
    | '/api/auth/$'
    | '/api/documents/$slug'
    | '/dokumen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/wajib-pajak'
    | '/dokumen/$slug'
    | '/api/auth/$'
    | '/api/documents/$slug'
    | '/dokumen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/dokumen'
    | '/_authenticated/wajib-pajak'
    | '/_authenticated/dokumen/$slug'
    | '/api/auth/$'
    | '/api/documents/$slug'
    | '/_authenticated/dokumen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsSlugRoute: typeof ApiDocumentsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wajib-pajak': {
      id: '/_authenticated/wajib-pajak'
      path: '/wajib-pajak'
      fullPath: '/wajib-pajak'
      preLoaderRoute: typeof AuthenticatedWajibPajakRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dokumen': {
      id: '/_authenticated/dokumen'
      path: '/dokumen'
      fullPath: '/dokumen'
      preLoaderRoute: typeof AuthenticatedDokumenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dokumen/': {
      id: '/_authenticated/dokumen/'
      path: '/'
      fullPath: '/dokumen/'
      preLoaderRoute: typeof AuthenticatedDokumenIndexRouteImport
      parentRoute: typeof AuthenticatedDokumenRoute
    }
    '/api/documents/$slug': {
      id: '/api/documents/$slug'
      path: '/api/documents/$slug'
      fullPath: '/api/documents/$slug'
      preLoaderRoute: typeof ApiDocumentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dokumen/$slug': {
      id: '/_authenticated/dokumen/$slug'
      path: '/$slug'
      fullPath: '/dokumen/$slug'
      preLoaderRoute: typeof AuthenticatedDokumenSlugRouteImport
      parentRoute: typeof AuthenticatedDokumenRoute
    }
  }
}

interface AuthenticatedDokumenRouteChildren {
  AuthenticatedDokumenSlugRoute: typeof AuthenticatedDokumenSlugRoute
  AuthenticatedDokumenIndexRoute: typeof AuthenticatedDokumenIndexRoute
}

const AuthenticatedDokumenRouteChildren: AuthenticatedDokumenRouteChildren = {
  AuthenticatedDokumenSlugRoute: AuthenticatedDokumenSlugRoute,
  AuthenticatedDokumenIndexRoute: AuthenticatedDokumenIndexRoute,
}

const AuthenticatedDokumenRouteWithChildren =
  AuthenticatedDokumenRoute._addFileChildren(AuthenticatedDokumenRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDokumenRoute: typeof AuthenticatedDokumenRouteWithChildren
  AuthenticatedWajibPajakRoute: typeof AuthenticatedWajibPajakRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDokumenRoute: AuthenticatedDokumenRouteWithChildren,
  AuthenticatedWajibPajakRoute: AuthenticatedWajibPajakRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsSlugRoute: ApiDocumentsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
